language: cpp
compiler:
  - gcc-4.4
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu precise universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ precise-updates main restricted"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ precise-updates universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse"
  - sudo add-apt-repository ppa:izx/privat
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake gcc-4.4 g++-4.4 libgoogle-glog-dev
before_script:
  cmake -DCMAKE_CXX_COMPILER=g++-4.4 -DCMAKE_C_COMPILER=gcc-4.4 -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_VERBOSE_MAKEFILE=1 .
script: make check
branches:
  only:
    - master
notifications:
  recipients:
    - dln@eintr.org
  email:
    on_success: change
    on_failure: always
